clc; clear all;
basePath = 'C:\Projects\PAX_models\PAX_calibration\coefficients';
dirInfo = dir(basePath);
% Filter out only directories and exclude '.' and '..'
axles =string({dirInfo([dirInfo.isdir] & ~ismember({dirInfo.name}, {'.', '..'})).name});

fileStr = ["// lib\generated\data_axles.dart (generated by PAX_models\PAX_calibration\"+"generate_dart_calib_file.m)"
    ""
    ... "import 'dart:async';"
    ... "import 'package:messwerk_debugger/util/bmi_top.dart';"
    ... "import 'package:messwerk_debugger/util/logger.dart';"
    ];

% fileStr = [fileStr
%     "Future<void> configureCalibrationForBMI(String axleN) async {"
%     "  await BMI_top.reset();"
%     "  switch (axleN) {"
%     ];
% 
% for axleN = axles
%     coef_folder = "C:\Projects\PAX_models\PAX_calibration\coefficients";
%     calibCubeCoefFile =        coef_folder+ "\"+num2str(axleN)+'\calibCubeCoefFile.tdms'       ;
%     calibRotCoefFile =         coef_folder+ "\"+num2str(axleN)+'\calibRotCoefFile.tdms'        ;
%     calibTemperatureCoefFile = coef_folder+ "\"+num2str(axleN)+'\calibTemperatureCoefFile.tdms';
%     calibForceCoefFile =       coef_folder+ "\"+num2str(axleN)+'\calibForceCoefFile.tdms'      ;
% 
% 
% 
%     fileStr(end+1)="    case """+axleN+""":";
%     % fileStr(end+1)="      await BMI_top.setAComp("+strrep(mat2str(TDMS_getStruct(char(calibCubeCoefFile)).Calibration.CompensationMatrix.data)," ",", ")+");";
%     fileStr(end+1)="      await BMI_top.setAComp("+strrep(mat2str(reshape(reshape(TDMS_getStruct(char(calibCubeCoefFile)).Calibration.CompensationMatrix.data,[],3)',1,[]))," ",", ")+");";
%     % fileStr(end+1)="      await BMI_top.setOmegaComp("+strrep(mat2str(TDMS_getStruct(char(calibRotCoefFile)).Calibration.CompensationMatrix.data)," ",", ")+");";
%     fileStr(end+1)="      await BMI_top.setOmegaComp("+strrep(mat2str(reshape(reshape(TDMS_getStruct(char(calibRotCoefFile)).Calibration.CompensationMatrix.data,[],3)',1,[]))," ",", ")+");";
%     fileStr(end+1)="      await BMI_top.r_IMU("+strrep(mat2str(TDMS_getStruct(char(calibRotCoefFile)).Props.r_IMU)," ",", ")+");";
%     % fileStr(end+1)="      await BMI_top.setTempComp("+strrep(mat2str(TDMS_getStruct(char(calibTemperatureCoefFile)).Calibration.coeffs.data)," ",", ")+");";
%     fileStr(end+1)="      await BMI_top.setTempComp("+strrep(mat2str(reshape(reshape(TDMS_getStruct(char(calibTemperatureCoefFile)).Calibration.coeffs.data,[],4)',1,[]))," ",", ")+");";
%     % fileStr(end+1)="      await BMI_top.setForceComp("+strrep(mat2str(TDMS_getStruct(char(calibForceCoefFile)).Calibration.coeffs.data)," ",", ")+");";
%     fileStr(end+1)="      await BMI_top.setForceComp("+strrep(mat2str(reshape(reshape(TDMS_getStruct(char(calibForceCoefFile)).Calibration.coeffs.data,[],2)',1,[]))," ",", ")+");";
%     fileStr(end+1)="";
% end
% fileStr = [fileStr;
% "    default:"
% "      log('Unsupported axle count: $axleN');"
% "      throw ArgumentError(""Unsupported axle count in configureBMI: $axleN"");"
% "  }"
% "}"
% ];

% % Define ID-to-MAC mapping (example: hardcoded, replace with actual data source if available)
% % Assume a structure where each axleN maps to a MAC address
% idToMac = containers.Map('KeyType', 'double', 'ValueType', 'char');
% for axleN = axles
%     % Example MAC address format: '00:1A:2B:3C:4D:' + axleN (padded to 2 digits)
%     idToMac(axleN) = sprintf('00:1A:2B:3C:4D:%02d', axleN);
% end

% Generate the ID-to-MAC conversion function
fileStr = [fileStr;
    "// Function to convert between ID and MAC address"
    "String? convertIdToMac(String id) {"
    "  const idToMac = {"
];

% Add ID-to-MAC mappings
for axleN = axles
    [~,MAC,~] = ID2MAC(axleN);
    fileStr(end+1) = sprintf("    '%s': '%s',", axleN, MAC);
end

fileStr = [fileStr;
    "  };"
    "  return idToMac[id];"
    "}"
    ""
    "String? convertMacToId(String mac) {"
    "  const macToId = {"
];

for axleN = axles
    [~,MAC,~] = ID2MAC(axleN);
    fileStr(end+1) = sprintf("    '%s': '%s',", MAC, axleN);
    assert(strlength(MAC)==17)
end

fileStr = [fileStr;
    "  };"
    "  return macToId[mac];"
    "}"
];

disp(join(fileStr,newline));
